language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
install:
    - "pip install pylint --use-mirrors"
    - "pip install coverage --use-mirrors"
    - "pip install sqlalchemy --use-mirrors"
    - "pip install rpyc --use-mirrors"
    - "pip install pygame --use-mirrors"
    - "pip install pyyaml --use-mirrors"
# command to run tests
script: 
    - nosetests --with-coverage
    - pylint --rcfile=pylint.conf fitg
